Лабораторная работа №1
pigeonmaster420/OmSTU-22-23-4 pull request #1
Opened 2022-11-30 06:37 UTC by pigeonmaster420

Плескач Александр/Голубь владислав

2022-11-30 06:59 UTC, zaryanezrya requested changes

2022-11-30 06:59 UTC, zaryanezrya commented on .github/workflows/dotnet.yml
> +    branches: [ "lab1" ]
Убрать триггер на пуш, добавить ручной триггер

2022-11-30 06:59 UTC, zaryanezrya commented on .vscode/launch.json
> +{
Удалить

2022-11-30 06:59 UTC, zaryanezrya commented on .vscode/tasks.json
> +{
Удалить

2022-11-30 06:59 UTC, zaryanezrya commented on SpaceBattle.lib/Rational.cs
> +public class rational
[Название классов, методов и т.д.](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#pascal-case)

2022-11-30 06:59 UTC, zaryanezrya commented on SpaceBattle.lib/Rational.cs
> +    public int a;
Наружу зачем торчит? Не нужно.
Если для сравнения, то нужно определить операторы для сравнения.

2022-11-30 07:17 UTC, pigeonmaster420 commented on .github/workflows/dotnet.yml
> +    branches: [ "lab1" ]
Добавлено

2022-11-30 07:17 UTC, pigeonmaster420 commented on .vscode/launch.json
> +{
Удалено

2022-11-30 07:17 UTC, pigeonmaster420 commented on .vscode/tasks.json
> +{
Удалено

2022-12-06 07:34 UTC, pigeonmaster420 commented on SpaceBattle.lib/Rational.cs
> +public class rational
Переименовано

2022-12-06 07:35 UTC, pigeonmaster420 commented on SpaceBattle.lib/Rational.cs
> +    public int a;
Исправлено

2022-12-06 07:46 UTC, zaryanezrya approved these changes

2022-12-29 17:37 UTC, closed without merging